### ISSUE TITLE
底部footer在移动端显示

### ISSUE THREAD

**Issue by Pikaconan** [AlanDecode/Maverick-Theme-Kepler#2]
如图
![l2twZR.png](https://s2.ax1x.com/2020/01/08/l2twZR.png)

**Comment by AlanDecode** [comment]
设计为可滚动。

**Comment by Pikaconan** [comment]
emmm，明白了，假如将备案号放置到 copyright 下方，未必比现在美观。或许我该删掉又拍云字样。
