### ISSUE TITLE
阅读量和访问量

### ISSUE THREAD

**Issue by mikamichael** [AlanDecode/Maverick-Theme-Kepler#3]
是否可以增加阅读量和访问量的代码？

**Comment by AlanDecode** [comment]
1. 静态博客本身没法实现统计
2. Kepler支持的 Valine 评论框架自带了阅读统计

**Comment by mikamichael** [comment]
请问，如何开启Valine评论框架？

**Comment by AlanDecode** [comment]
请参见 https://github.com/AlanDecode/Maverick#comments
